apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kustomize-build
  labels:
    app.kubernetes.io/name: gitops-ci
spec:
  description: Runs kustomize build for an overlay
  params:
    - name: overlay-path
      type: string
    - name: image
      type: string
      default: ghcr.io/arthurvardevanyan/k8s-gitops-ci:latest
  workspaces:
    - name: source
  steps:
    - name: build
      image: $(params.image)
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        kustomize build "$(params.overlay-path)"
