// Code generated by scripts/pull-scoped-resources.sh. DO NOT EDIT.
// Add org-specific scopes here; merge-only, never removes built-ins.
// Keys use "apiGroup/Kind" format; true = cluster-scoped, false = namespace-scoped.

package namespace

// ExtraResourceScope allows org layers to extend resourceScope without edits.
var ExtraResourceScope = map[string]bool{}
