#!/usr/bin/env bash
set -euo pipefail

: "${OUTPUT:=pkg/validator/namespace/resource_scope.go}"
: "${EXTRA_OUTPUT:=pkg/validator/namespace/extra_resource_scope.go}"

if ! command -v kubectl >/dev/null 2>&1; then
  echo "ERROR: kubectl is required to generate resource scopes" >&2
  exit 1
fi

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

# Collect namespace-scoped resources.
# kubectl api-resources outputs a table; with --no-headers the columns are:
#   NAME  [SHORTNAMES]  APIVERSION  NAMESPACED  KIND
# SHORTNAMES may be absent, so we use $NF (KIND) and $(NF-2) (APIVERSION)
# which remain stable regardless of whether SHORTNAMES is present.
kubectl api-resources --verbs=list --namespaced --no-headers 2>/dev/null | \
  awk '{
    apiVersion = $(NF-2)
    kind       = $NF
    n = split(apiVersion, parts, "/")
    group = (n >= 2) ? parts[1] : ""
    printf "  \"%s/%s\": false,\n", group, kind
  }' | sort -u > "$TMP_DIR/namespaced_entries.txt" || true

# Collect cluster-scoped resources (true = cluster-scoped).
kubectl api-resources --verbs=list --namespaced=false --no-headers 2>/dev/null | \
  awk '{
    apiVersion = $(NF-2)
    kind       = $NF
    n = split(apiVersion, parts, "/")
    group = (n >= 2) ? parts[1] : ""
    printf "  \"%s/%s\": true,\n", group, kind
  }' | sort -u > "$TMP_DIR/cluster_entries.txt" || true

if [[ ! -s "$TMP_DIR/namespaced_entries.txt" && ! -s "$TMP_DIR/cluster_entries.txt" ]]; then
  echo "WARNING: kubectl returned no api-resources; output unchanged" >&2
  exit 0
fi

cat > "$OUTPUT" <<'HEADER'
// Code generated by scripts/pull-scoped-resources.sh. DO NOT EDIT.
// To regenerate from a live cluster: task update:scoped-resources

package namespace

// resourceScope maps "apiGroup/Kind" to its scope.
// true = cluster-scoped (no namespace required), false = namespace-scoped (namespace required).
// Core API resources use an empty group: "/Namespace", "/Service", etc.
// Resources not present in this map are unknown and will fail validation.
var resourceScope = map[string]bool{
HEADER

cat "$TMP_DIR/namespaced_entries.txt" "$TMP_DIR/cluster_entries.txt" >> "$OUTPUT"

cat >> "$OUTPUT" <<'FOOTER'
}
FOOTER

cat > "$EXTRA_OUTPUT" <<'HEADER'
// Code generated by scripts/pull-scoped-resources.sh. DO NOT EDIT.
// Add org-specific scopes here; merge-only, never removes built-ins.
// Keys use "apiGroup/Kind" format; true = cluster-scoped, false = namespace-scoped.

package namespace

// ExtraResourceScope allows org layers to extend resourceScope without edits.
var ExtraResourceScope = map[string]bool{
HEADER

# Org-specific entries: set ORG_DOMAINS to a space-separated list of API groups
# whose Kinds should be registered. Since the script cannot know the Kind names
# for arbitrary groups, add entries manually after generation in the format:
#   "my.domain.io/MyKind": true,   // cluster-scoped
#   "my.domain.io/MyOther": false, // namespace-scoped
if [[ -n "${ORG_DOMAINS:-}" ]]; then
  echo "  // NOTE: ORG_DOMAINS entries below need manual Kind names added" >> "$EXTRA_OUTPUT"
  for domain in $ORG_DOMAINS; do
    printf '  // "%s/<Kind>": true,\n' "$domain" >> "$EXTRA_OUTPUT"
  done
fi

cat >> "$EXTRA_OUTPUT" <<'FOOTER'
}
FOOTER

echo "Wrote $OUTPUT and $EXTRA_OUTPUT"
