#!/usr/bin/env bash
set -euo pipefail

: "${OUTPUT:=pkg/validator/namespace/resource_scope.go}"
: "${EXTRA_OUTPUT:=pkg/validator/namespace/extra_resource_scope.go}"

org_domains=""
if [[ -n "${ORG_DOMAINS:-}" ]]; then
  org_domains="$ORG_DOMAINS"
fi

if ! command -v kubectl >/dev/null 2>&1; then
  echo "ERROR: kubectl is required to generate resource scopes" >&2
  exit 1
fi

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

kubectl api-resources --verbs=list --namespaced -o name 2>/dev/null | sort -u > "$TMP_DIR/namespaced.txt" || true
kubectl api-resources --verbs=list --namespaced=false -o name 2>/dev/null | sort -u > "$TMP_DIR/cluster.txt" || true

if [[ ! -s "$TMP_DIR/namespaced.txt" && ! -s "$TMP_DIR/cluster.txt" ]]; then
  echo "WARNING: kubectl returned no api-resources; output unchanged" >&2
  exit 0
fi

cat > "$OUTPUT" <<'HEADER'
// Code generated by scripts/pull-scoped-resources.sh. DO NOT EDIT.

package namespace

// resourceScope maps apiVersion/kind to expected namespace scope.
var resourceScope = map[string]string{
HEADER

write_map() {
  while IFS='/' read -r group kind; do
    if [[ -z "$group" || -z "$kind" ]]; then
      continue
    fi
    printf '  "%s/%s": "%s",\n' "$group" "$kind" "$1"
  done
}

write_map "namespaced" < "$TMP_DIR/namespaced.txt" >> "$OUTPUT"
write_map "cluster" < "$TMP_DIR/cluster.txt" >> "$OUTPUT"

cat >> "$OUTPUT" <<'FOOTER'
}
FOOTER

cat > "$EXTRA_OUTPUT" <<'HEADER'
// Code generated by scripts/pull-scoped-resources.sh. DO NOT EDIT.
// Add org-specific scopes here; merge-only, never removes built-ins.

package namespace

// ExtraResourceScope allows org layers to extend resourceScope without edits.
var ExtraResourceScope = map[string]string{
HEADER

if [[ -n "$org_domains" ]]; then
  for domain in $org_domains; do
    printf '  "%s/v1": "cluster",\n' "$domain" >> "$EXTRA_OUTPUT"
  done
fi

cat >> "$EXTRA_OUTPUT" <<'FOOTER'
}
FOOTER

echo "Wrote $OUTPUT and $EXTRA_OUTPUT"
