#!/usr/bin/env bash
set -euo pipefail

# Force byte-order (ASCII) sorting everywhere in this script. Under a
# linguistic locale (e.g. en_US.UTF-8), `sort` treats punctuation specially
# and will sort "/Binding" (empty/core API group) *after* "aaq.kubevirt.io/..."
# instead of before it, scattering the core "/Kind" entries throughout the
# generated map instead of grouping them at the top as expected.
export LC_ALL=C

: "${OUTPUT:=pkg/validator/static/namespace/resource_scope.go}"
: "${EXTRA_OUTPUT:=pkg/validator/static/namespace/extra_resource_scope.go}"

if ! command -v kubectl >/dev/null 2>&1; then
  echo "ERROR: kubectl is required to generate resource scopes" >&2
  exit 1
fi

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

# Collect namespace-scoped resources.
# kubectl api-resources outputs a table; with --no-headers the columns are:
#   NAME  [SHORTNAMES]  APIVERSION  NAMESPACED  KIND
# SHORTNAMES may be absent, so we use $NF (KIND) and $(NF-2) (APIVERSION)
# which remain stable regardless of whether SHORTNAMES is present.
kubectl api-resources --verbs=list --namespaced --no-headers 2>/dev/null | \
  awk '{
    apiVersion = $(NF-2)
    kind       = $NF
    n = split(apiVersion, parts, "/")
    group = (n >= 2) ? parts[1] : ""
    printf "  \"%s/%s\": false,\n", group, kind
  }' | sort -u > "$TMP_DIR/namespaced_entries.txt" || true

# Collect cluster-scoped resources (true = cluster-scoped).
kubectl api-resources --verbs=list --namespaced=false --no-headers 2>/dev/null | \
  awk '{
    apiVersion = $(NF-2)
    kind       = $NF
    n = split(apiVersion, parts, "/")
    group = (n >= 2) ? parts[1] : ""
    printf "  \"%s/%s\": true,\n", group, kind
  }' | sort -u > "$TMP_DIR/cluster_entries.txt" || true

cat "$TMP_DIR/namespaced_entries.txt" "$TMP_DIR/cluster_entries.txt" > "$TMP_DIR/new_entries.txt"

if [[ ! -s "$TMP_DIR/new_entries.txt" ]]; then
  echo "WARNING: kubectl returned no api-resources; output unchanged" >&2
  exit 0
fi

# This map is a cumulative record of every Kind ever seen across any cluster
# this has been run against, not just the current one. Different clusters
# expose different CRDs/APIs, so a single run only ever sees a subset. To
# avoid dropping entries learned from previous runs against other clusters,
# merge the freshly discovered entries with whatever is already on disk:
# new entries win on conflicting scope values, but entries only present in
# the existing file (not seen this run) are preserved rather than deleted.
if [[ -f "$OUTPUT" ]]; then
  grep -E '^[[:space:]]*"[^"]+":[[:space:]]*(true|false),' "$OUTPUT" > "$TMP_DIR/existing_entries.txt" || true
else
  : > "$TMP_DIR/existing_entries.txt"
fi

awk '
  {
    line = $0
    gsub(/^[ \t]+/, "", line)
    pos = index(line, "\": ")
    if (pos == 0) { next }
    key = substr(line, 1, pos + 1)
    if (!(key in seen)) {
      seen[key] = 1
      # Normalize indentation so lines carried over from a previously
      # gofmt-tabbed $OUTPUT (leading "\t") and freshly discovered entries
      # (leading "  ") sort together by key instead of bucketing by
      # whichever whitespace character happens to precede the quote (tab
      # sorts before space in ASCII, which would otherwise group all
      # preserved entries before all newly discovered ones).
      print "  " line
    }
  }
' "$TMP_DIR/new_entries.txt" "$TMP_DIR/existing_entries.txt" | sort -u > "$TMP_DIR/merged_entries.txt"

cat > "$OUTPUT" <<'HEADER'
// Code generated by scripts/pull-scoped-resources.sh. DO NOT EDIT.
// To regenerate from a live cluster: task update:scoped-resources
// This file is cumulative across runs/clusters: re-running merges newly
// discovered Kinds into the existing map rather than replacing it, so Kinds
// only present on other clusters are not lost.

package namespace

// resourceScope maps "apiGroup/Kind" to its scope.
// true = cluster-scoped (no namespace required), false = namespace-scoped (namespace required).
// Core API resources use an empty group: "/Namespace", "/Service", etc.
// Resources not present in this map are unknown and will fail validation.
var resourceScope = map[string]bool{
HEADER

cat "$TMP_DIR/merged_entries.txt" >> "$OUTPUT"

cat >> "$OUTPUT" <<'FOOTER'
}
FOOTER

# EXTRA_OUTPUT holds manually curated org-specific entries (see the comment
# in its own header). Unlike $OUTPUT, its contents are never derived from
# kubectl, so regenerating must never clobber whatever the user has hand-
# edited into it: preserve the existing map body verbatim and only append
# placeholders for any newly requested ORG_DOMAINS that aren't already noted.
EXISTING_EXTRA_BODY="$TMP_DIR/existing_extra_body.txt"
: > "$EXISTING_EXTRA_BODY"
if [[ -f "$EXTRA_OUTPUT" ]]; then
  awk '
    /var ExtraResourceScope = map\[string\]bool\{/ { flag = 1; next }
    flag && /^}/ { flag = 0; next }
    flag { print }
  ' "$EXTRA_OUTPUT" > "$EXISTING_EXTRA_BODY"
fi

cat > "$EXTRA_OUTPUT" <<'HEADER'
// Code generated by scripts/pull-scoped-resources.sh. DO NOT EDIT.
// Add org-specific scopes here; merge-only, never removes built-ins.
// Keys use "apiGroup/Kind" format; true = cluster-scoped, false = namespace-scoped.

package namespace

// ExtraResourceScope allows org layers to extend resourceScope without edits.
var ExtraResourceScope = map[string]bool{
HEADER

cat "$EXISTING_EXTRA_BODY" >> "$EXTRA_OUTPUT"

# Org-specific entries: set ORG_DOMAINS to a space-separated list of API groups
# whose Kinds should be registered. Since the script cannot know the Kind names
# for arbitrary groups, add entries manually after generation in the format:
#   "my.domain.io/MyKind": true,   // cluster-scoped
#   "my.domain.io/MyOther": false, // namespace-scoped
if [[ -n "${ORG_DOMAINS:-}" ]]; then
  for domain in $ORG_DOMAINS; do
    if ! grep -qF "\"$domain/" "$EXISTING_EXTRA_BODY" 2>/dev/null; then
      printf '  // "%s/<Kind>": true, // TODO: fill in Kind and correct scope\n' "$domain" >> "$EXTRA_OUTPUT"
    fi
  done
fi

cat >> "$EXTRA_OUTPUT" <<'FOOTER'
}
FOOTER

echo "Wrote $OUTPUT and $EXTRA_OUTPUT"
